import { Inter } from "next/font/google";
import "./globals.css";
import Nabvar from "@/components/Shared/Nabvar";
import Footer from "@/components/Shared/Footer";
import AuthProvider from "@/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Restro Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Nabvar />
          <div>{children}</div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
